# Generated by Django 3.2.7 on 2021-10-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='picture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='user',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
